@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Component.puml

title Rental Service - Componentes

Container_Boundary(rental_service, "Rental Service") {

    Component(rental_api, "Rental API", "REST Controller", "Recebe requisições")

    Component(rental_application, "Rental Application Service", "Application Layer", "Orquestra regras de negócio")

    Component(reservation_engine, "Reservation Engine", "Domain Service", "Gerencia disponibilidade")

    Component(pricing_service, "Pricing Service", "Domain Service", "Calcula preços")

    Component(contract_service, "Contract Service", "Domain Service", "Gera contratos")

    Component(rental_repository, "Rental Repository", "Repository", "Persistência")

    Component(event_publisher, "Event Publisher", "Messaging", "Publica eventos")

}

ContainerDb(rental_db, "Rental DB", "PostgreSQL")

Container(message_broker, "Message Broker", "Kafka")

Rel(rental_api, rental_application, "Usa")

Rel(rental_application, reservation_engine, "Consulta disponibilidade")
Rel(rental_application, pricing_service, "Calcula preço")
Rel(rental_application, contract_service, "Cria contrato")

Rel(rental_application, rental_repository, "Salva reserva")

Rel(rental_repository, rental_db, "R/W")

Rel(rental_application, event_publisher, "Publica eventos")
Rel(event_publisher, message_broker, "Envia evento")



'' Veiculos

title Vehicle Service - Componentes

Container_Boundary(vehicle_service, "Vehicle Service") {

    Component(vehicle_api, "Vehicle API", "REST Controller", "Recebe requisições")

    Component(vehicle_security_service, "Vehicle Security Service", "Application Layer", "Orquestra regras de negócio")
    
    Component(vehicle_application, "Vehicle Application Service", "Application Layer", "Orquestra regras de negócio")

    Component(vehicle_repository, "Vehicle Repository", "Repository", "Persistência")

    Component(vehicle_event_publisher, "Event Publisher", "Messaging", "Publica eventos")

}

ContainerDb(vehicle_db, "Vehicle DB", "PostgreSQL")

Container(message_broker, "Message Broker", "Kafka")

Rel(vehicle_api, vehicle_security_service, "Autentica usuário")
Rel(vehicle_api, vehicle_application, "Regras de negocio")
Rel(vehicle_application, vehicle_repository, "Persistência")
Rel(vehicle_application, vehicle_event_publisher, "Publica eventos e mensagens")

Rel(vehicle_repository, vehicle_db, "R/W")


'' Payment

title Payment Service - Componentes

Container_Boundary(payment_service, "Payment Service") {

    Component(payment_api, "Payment API", "REST Controller", "Recebe requisições")

    Component(payment_security_service, "Payment Security Service", "Application Layer", "Orquestra regras de negócio")
    
    Component(payment_application, "Payment Application Service", "Application Layer", "Orquestra regras de negócio")

    Component(payment_repository, "Payment Repository", "Repository", "Persistência")

    Component(payment_event_publisher, "Event Publisher", "Messaging", "Publica eventos")

}

ContainerDb(payment_db, "Payment DB", "PostgreSQL")

Container(message_broker, "Message Broker", "Kafka")

Rel(payment_api, payment_security_service, "Autentica usuário")
Rel(payment_api, payment_application, "Regras de negocio")
Rel(payment_application, payment_repository, "Persistência")
Rel(payment_application, payment_event_publisher, "Publica eventos e mensagens")

Rel(payment_repository, payment_db, "R/W")
@enduml