@startuml
!include https://raw.githubusercontent.com/plantuml-stdlib/C4-PlantUML/master/C4_Container.puml

title Plataforma de Locação - Containers

Person(customer, "Cliente")
Person(operador, "Operador")

System_Boundary(system, "Plataforma de Locação") {

    Container(web_app, "Web App", "React / SPA", "Interface do usuário")

    Container(api_gateway, "API Gateway", "Kong / Nginx", "Ponto de entrada das APIs")

    Container(user_service, "User Service", "Backend Service", "Gerenciamento de usuários")

    Container(vehicle_service, "Vehicle Service", "Backend Service", "Gerenciamento de veículos")

    Container(rental_service, "Rental Service", "Backend Service", "Reservas e contratos")

    Container(payment_service, "Payment Service", "Backend Service", "Orquestra pagamentos")

    Container(notification_service, "Notification Service", "Worker Service", "Envio de emails e SMS")

    ContainerDb(user_db, "User DB", "PostgreSQL")
    ContainerDb(vehicle_db, "Vehicle DB", "PostgreSQL")
    ContainerDb(rental_db, "Rental DB", "PostgreSQL")
    
    Container(message_broker, "Message Broker", "Kafka / RabbitMQ")
}

Rel(customer, web_app, "Usa")
Rel(operador, web_app, "Opera")

Rel(web_app, api_gateway, "HTTPS")

Rel(api_gateway, user_service, "User API")
Rel(api_gateway, vehicle_service, "Vehicle API")
Rel(api_gateway, rental_service, "Rental API")

Rel(user_service, user_db, "R/W")
Rel(vehicle_service, vehicle_db, "R/W")
Rel(rental_service, rental_db, "R/W")

Rel(user_service, message_broker, "Publica eventos de notificação")
BiRel(rental_service, message_broker, "Publica eventos")
BiRel(payment_service, message_broker, "Publica eventos")
Rel( message_broker, notification_service, "Consome eventos")

@enduml