# Este arquivo define a estrutura base.
# Valores genéricos ou fixos ficam aqui.

# Deixamos campos obrigatórios vazios ou com placeholders
# para garantir que o app valide a existência deles.
database_url = "postgres://postgres:postgres@localhost:5432/notification_service"
jwt_secret = "0aa59f4d8621d8e18db9f037618afd0443433f25fdcfd8d77aee276a37e3a6ac"
show_time_tracing_logs = true
time_tracing_logs_with_ansi = false
