database_url = "postgres://postgres:postgres@localhost:5432/pantera"
jwt_secret = "0aa59f4d8621d8e18db9f037618afd0443433f25fdcfd8d77aee276a37e3a6ac"

show_time_tracing_logs = true
time_tracing_logs_with_ansi = true
